version: '3'
services:
    bot:
        container_name: sentry
        build:
            context: ./
            dockerfile: Dockerfile-dev
        volumes:
            - ./:/usr/src/app
        depends_on:
            - postgres
        command:
            [
                './scripts/wait-for-it.sh',
                'postgres:5432',
                '--',
                'npm',
                'run',
                'start:dev',
            ]
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: sentry
        ports:
            - 5432:5432
        volumes:
            - ./.postgres:/var/lib/postgresql/data
    adminer:
        image: adminer
        restart: always
        ports:
            - 9000:8080
volumes:
    data:
